CREATE TABLE USER (
	NAME VARCHAR PRIMARY KEY NOT NULL,
	PASSWORD VARCHAR NOT NULL
);


CREATE TABLE FRIENDS (
	NAME1 VARCHAR NOT NULL,
	NAME2 VARCHAR NOT NULL,
	PRIMARY KEY (NAME1, NAME2),
	FOREIGN KEY (NAME1) REFERENCES USER(NAME),
	FOREIGN KEY (NAME2) REFERENCES USER(NAME)
);


CREATE TABLE GAME (
	NAME1 VARCHAR NOT NULL,
	NAME2 VARCHAR NOT NULL,
	TURN_COUNTER INT,
	SCORE1 INT,
	SCORE2 INT,
	VIDEO TEXT,
	PRIMARY KEY (NAME1, NAME2),
	FOREIGN KEY (NAME1) REFERENCES FRIENDS(NAME1),
	FOREIGN KEY (NAME2) REFERENCES FRIENDS(NAME2)
);
